version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/skadoosh:latest
    working_directory: /home/alpine/circle/
    steps:
      - run:
          name: Initialize
          command: df -hlT
